api:
  url: https://openweathermap.org/api

config:
  name: Configuration Task

server:
  port: 8080

spring:
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/OrderFoodDB
    username: postgres
    password: mahtab23898
    initialization-mode: always
    initialize: true
    continue-on-error: true
